# Generated by Django 2.2 on 2021-07-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_app', '0002_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowManager',
        ),
    ]
