# Generated by Django 2.2 on 2021-07-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantedwish',
            name='wish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wishListApp.Wish'),
        ),
    ]
